// <auto-generated />
using EmployeeManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementAPI.Migrations
{
    [DbContext(typeof(EmpDbcontext))]
    [Migration("20260328105710_Emailtypechange")]
    partial class Emailtypechange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementAPI.Models.Employee", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("EmpId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpDepartment");

                    b.Property<string>("Email")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpEmail");

                    b.Property<string>("ImagePath")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpImage");

                    b.Property<string>("Name")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpName");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserEmail");

                    b.Property<string>("Password")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserPassword");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
