// <auto-generated />
using System;
using EmployeeManagementAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementAPI.Migrations
{
    [DbContext(typeof(EmpDbcontext))]
    partial class EmpDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementAPI.Models.EmpDepartment", b =>
                {
                    b.Property<decimal>("EmpDepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("EmpDep_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("EmpDepId"));

                    b.Property<string>("EmpDepName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpDep_Name");

                    b.Property<int>("EmpDepStatus")
                        .HasColumnType("Int")
                        .HasColumnName("EmpDep_Status");

                    b.HasKey("EmpDepId");

                    b.ToTable("EmpDepartments");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.Employee", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("EmpId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmpCity");

                    b.Property<string>("Department")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpDepartment");

                    b.Property<string>("Email")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpEmail");

                    b.Property<DateTime>("EmpDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpImage");

                    b.Property<string>("MobileNo")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpMobileNo");

                    b.Property<string>("Name")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("EmpName");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeManagementAPI.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserEmail");

                    b.Property<string>("Name")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserName");

                    b.Property<string>("Password")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserPassword");

                    b.Property<decimal>("UserType")
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("UserType");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
